<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="Serilog.Enrichers.AspNetCore.HttpContext" Version="1.0.1" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
		<PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.ExceptionStackTraceHash" Version="1.3.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Extensions\Utils\Email\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FinanceControl.Domain\FinanceControl.Domain.csproj" />
	  <ProjectReference Include="..\FinanceControl.Infra\FinanceControl.Infra.csproj" />
	</ItemGroup>

</Project>
